{{- if .Values.externalSecrets.enabled }}
{{- $secretStoreName := .Values.externalSecrets.secretStore.name }}
{{- range $secret := .Values.externalSecrets.secrets }}
{{- $existing := (lookup "external-secrets.io/v1" "ExternalSecret" $.Release.Namespace $secret.name) }}
{{- if not $existing }}
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ $secret.name }}
spec:
  secretStoreRef:
    name: {{ $secretStoreName }}
    kind: SecretStore
  refreshInterval: {{ default "10m" $secret.refreshInterval }}
  target:
    name: {{ $secret.name }}
    creationPolicy: Owner
  data:
  {{- range $item := $secret.data }}
  - secretKey: {{ $item.secretKey }}
    remoteRef:
      key: {{ $item.remoteRefKey }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
