apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
  name: {{ .Values.frontend.appName }}-service
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app: {{ .Values.frontend.appName }}
  ports:
    - protocol: TCP
      port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
