apiVersion: v1
kind: Secret
metadata:
  name: wordpress-db-secret
type: Opaque
stringData:
  WORDPRESS_DB_HOST: your-azure-db-host
  WORDPRESS_DB_USER: your-db-username
  WORDPRESS_DB_PASSWORD: your-db-password
  WORDPRESS_DB_NAME: your-db-name
