{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://{{ .Values.externalSecrets.secretStore.azureKeyVaultName }}.vault.azure.net"
      serviceAccountRef:
        name: {{ .Values.externalSecrets.secretStore.serviceAccountName }}
{{- end }}
