{{- if .Values.externalSecrets.enabled }}
apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ .Values.externalSecrets.secretStore.name }}
  labels:
    {{- include "joyforum.labels" . | nindent 4 }}
spec:
  provider:
    azurekv:
      authType: WorkloadIdentity
      vaultUrl: "https://{{ .Values.externalSecrets.secretStore.azureKeyVaultName }}.vault.azure.net"
      tenantId: {{ .Values.externalSecrets.secretStore.tenantId | quote }}
      serviceAccountRef:
        name: {{ .Values.externalSecrets.secretStore.serviceAccountName }}
{{- end }}
